### ISSUE TITLE
Easy way to convert from any array to a column-major (f-layout) array?

### ISSUE THREAD

**Issue by multimeric** [rust-ndarray/ndarray#1060]
Hi, I'm working on `extendr` ie Rust bindings for R. Now R uses exclusively column-major array layouts, so to converting an `ArrayBase` to an R array/vector means first making the array column-major.

 My current PR in `extendr` is here: https://github.com/extendr/extendr/pull/275. What I'm currently doing is this:
```rust
        let reshaped: ArrayView<A, D>;
        if arr.is_standard_layout() {
            // If we have a standard layout array, we have to transpose the array
            reshaped = arr.t();
        } else {
            // If we have a fortran layout array, we can keep the current memory layout
            reshaped = arr.view();
            dims = inverse.shape().iter().map(|x| *x as i32).collect();
        }
```
Just wondering if:

1. There's a built-in way to do this, that doesn't require an if-else?
2. Will `.t()` always make a C-layout array into an F-layout array? What if it's 3-dimensional?
3. Is using `is_standard_layout()` equivalent to asking if it's F-layout? Is it possible for it to be neither, and this code breaks?
4. How can I make an array into F-layout without transposing the dimensions. For example, an ndarray array with 2 rows and 3 columns that is in C order can be made into F order using `.t()` **but**, doing this will set the dimensions to `(3, 2)`, which isn't actually correct: there are still only 2 rows and 3 columns, only the layout has changed.

**Comment by jturner314** [comment]
Do you need an owned array, or is a `CowArray` sufficient?

It would help to have some definitions. [The core of the `is_standard_layout` implementation is here.](https://github.com/rust-ndarray/ndarray/blob/0.15.3/src/dimension/mod.rs#L671-L694) I'll call arrays for which this returns `true` "C-layout arrays". F-layout arrays are like C-layout arrays, except that the strides are in ascending order instead of descending order.

> 1. There's a built-in way to do this, that doesn't require an if-else?

If all you need is a `CowArray`, then you could use `arr.t().as_standard_layout().reversed_axes()`.

> 2. Will `.t()` always make a C-layout array into an F-layout array? What if it's 3-dimensional?

Yes. `.t()` and `.reversed_axes()` simply reverse the order of the shape and strides; they don't alter the data in any way.

> 3. Is using `is_standard_layout()` equivalent to asking if it's F-layout? Is it possible for it to be neither, and this code breaks?

`.is_standard_layout()` returns `true` if the array has C-layout. If it returns `false`, that does not necessarily imply that the array has F-layout. In other words, yes, it is possible for an array to be neither C-layout nor F-layout. If you want to check if an array has F-layout, then the simplest way is `arr.t().is_standard_layout()`.

> 4. How can I make an array into F-layout without transposing the dimensions. For example, an ndarray array with 2 rows and 3 columns that is in C order can be made into F order using `.t()` **but**, doing this will set the dimensions to `(3, 2)`, which isn't actually correct: there are still only 2 rows and 3 columns, only the layout has changed.

See my answer to question 1.

A couple of things to be careful about if you plan to pass the strides of an F-layout array to R:

- With `ndarray`, the strides of axes with length <= 1 are arbitrary, while R may require them to always be 0 or something, IDK.

- With `ndarray`, the strides of empty arrays (i.e. arrays which have at least one length 0 axis) may be surprising in some cases. For example, it's valid for all the strides of an empty array to be 0. R may expect certain values for the strides of empty arrays, IDK.

**Comment by multimeric** [comment]
Thanks for the great answer!

> Do you need an owned array, or is a CowArray sufficient?

I actually don't even need an array, I just need a slice, vector or iterator over each cell in F order.

> If all you need is a CowArray, then you could use arr.t().as_standard_layout().reversed_axes().

Do you mean to transpose this twice here? Also, is it more efficient to transpose before calling `as_standard_layout`, or after? 

> In other words, yes, it is possible for an array to be neither C-layout nor F-layout

In that case, is `arr.as_standard_layout().f()` always going to give me an F-layout array?

> A couple of things to be careful about if you plan to pass the strides of an F-layout array to R:

Thanks, I'll add some of these as test cases.

**Comment by jturner314** [comment]
> Do you mean to transpose this twice here?

Yes. I assumed that you wanted the array to have the same shape and elements, just with a different layout. The public API doesn't have an `as_fortran_layout` method, but we can approximate one by transposing the array, converting it to a C-layout array, and then transposing the result. If all you want is a slice, then you could do

```rust
let arr_f = arr.t().as_standard_layout().reversed_axes();
let slice = arr_f.as_slice_memory_order().expect("This should never panic.");
```

> Also, is it more efficient to transpose before calling `as_standard_layout`, or after?

`.t()` and `.reversed_axes()` have very little (near-zero) cost. They don't change the data; they simply reorder the shape and strides.

> In that case, is `arr.as_standard_layout().f()` always going to give me an F-layout array?

I think you meant `arr.as_standard_layout().t()`. In that case, yes, the result of that expression will always be an F-layout array.

**Comment by multimeric** [comment]
> The public API doesn't have an as_fortran_layout method, but we can approximate one by transposing the array, converting it to a C-layout array, and then transposing the result.

I'm still a bit confused by this. If `.as_standard_layout()` always makes it into a C-layout array, won't the `.t()` preceding it always be unused?

**Comment by jturner314** [comment]
I'm not sure I understand your question. Here's an example:

```rust
use ndarray::prelude::*;

fn main() {
    let arr = array![[1, 2, 3], [4, 5, 6]];
    println!("{:?}\n", arr);
    println!("{:?}\n", arr.as_standard_layout().reversed_axes());
    println!("{:?}\n", arr.t().as_standard_layout().reversed_axes());
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e694594cb3cada88674ab4201ecc76cc))

and the resulting output:

```
[[1, 2, 3],
 [4, 5, 6]], shape=[2, 3], strides=[3, 1], layout=Cc (0x5), const ndim=2

[[1, 4],
 [2, 5],
 [3, 6]], shape=[3, 2], strides=[1, 3], layout=Ff (0xa), const ndim=2

[[1, 2, 3],
 [4, 5, 6]], shape=[2, 3], strides=[1, 2], layout=Ff (0xa), const ndim=2
```

You can see that both `arr.as_standard_layout().reversed_axes()` and `arr.t().as_standard_layout().reversed_axes()` produce a F-layout array, but only one of them produces an array with the same shape and elements as `arr`.

**Comment by multimeric** [comment]
Thanks, this is very helpful, I'll just have to think a bit about why this works. On a related note, will this code also work if the starting array is already in F-layout? ie we created it using `Array::from_shape_vec((2, 3).f(), vec![1., 2., 3., 4., 5., 6.]).unwrap()`

**Comment by jturner314** [comment]
Yes, it works for arbitrary layouts. In fact, the ideal case is when the input is already in F-layout, since `arr.t().as_standard_layout().reversed_axes()` doesn't need to copy the data in that case.

**Comment by multimeric** [comment]
Great, thank you. Before I close this issue, do you see any issue with my existing solution of using `arr.as_standard_layout().t().iter()` to get an iterator over the elements of any array in Fortran order? This is slightly different from your solution because I don't need the array itself to be in this order, just the iterator, so I'm thinking it's okay that I don't transpose the array at the start?

**Comment by jturner314** [comment]
If you want an iterator in Fortran order, then the best approach would be `arr.t().iter()`. (`.iter()` always goes in "logical order" (i.e. C order), regardless of the array's memory layout, so `.iter()` on the transpose of the array will correspond to Fortran order. The `.as_standard_layout()` is unnecessary, and should be avoided because it would copy the contents of `arr` if it's not already in standard layout.)

**Comment by multimeric** [comment]
Great, thanks! I will use this to inform my `extendr` implementation.

Incidentally do you think you could move this thread into discussions? I'm not really sure why I posted it as an issue.

Also, I might try to write up some documentation summarising what you have said.

**Comment by bluss** [comment]
I think we can also mention `arr.to_shape((arr.dim(), Order::F))` here - as a way to get the same array in Fortran order as a CowArray, it's either a view or copying all elements if needed.

**Comment by multimeric** [comment]
Oh, that's a good tip I didn't know about.
