### ISSUE TITLE
Add maintainers/reviewers?

### ISSUE THREAD

**Issue by multimeric** [rust-ndarray/ndarray#1075]
Hi @bluss and @jturner314. I noticed that dev has stalled a little in the past few months. In particular there are a number of useful PRs and issues that haven't been addressed. I know this is mostly because @bluss is busy/away, but ideally the burden of the whole project wouldn't rest on one person to such an extent, especially considering how important this crate is in the Rust scientific ecosystem. I'm wondering if there is the scope to add maintainers or at least people at a lower level of the organisation to optimise the workflow a little.

For example, while I'm not yet at a point where I would want to have merge permissions, I would be happy to triage issues and review PRs as I have done here: https://github.com/rust-ndarray/ndarray/pull/1042#pullrequestreview-732964668 and https://github.com/rust-ndarray/ndarray/issues/1059#issuecomment-910097152. This would reduce the number of things that demand your attention, and you would only need to then review the polished PRs and think about the longer-term goals like the move to `ArrayRef` .

**Comment by jturner314** [comment]
@multimeric, thanks for your comments on the issues/PRs. I prefer to have @bluss's input on large design decisions, but for most things, I can merge when @bluss is away. Unfortunately, I'm very busy right now, too. I hope to have more time to work on `ndarray` a few months from now. A couple of other people have push access too (@LukeMathWalker and @xd009642), but they seem to be busy with other things. For now, I guess what would be most useful is to determine which of the PRs would be the most useful today without breaking changes, get them closer to being ready-to-merge, and then let me know so that I can review them when I have the time.

**Comment by bluss** [comment]
I'm happy that you want to help and that you care about ndarray.

It hasn't always been as easy as adding more maintainers, but I'd like to do that too. We need some more people on board. I have time mainly to work on the things I care about, which is not always matching other PRs that come up - that's also why we need other maintainers who can work on the areas they want to focus on. :)

**Comment by nilgoyette** [comment]
Closing this issue because https://github.com/rust-ndarray/ndarray/issues/1272 is more complete.
