### ISSUE TITLE
Iterators yielding borrowed data?

### ISSUE THREAD

**Issue by zmitchell** [rust-ndarray/ndarray#1135]
I'm trying to do a fold over a vector and the rows of an array, like this:
```rust
fn my_func(foo: &Array1<f32>, bar: &Array2<f32>) -> Array1<f32> {
    let weighted_sum = Zip::from(foo)
        .and(bar.rows())
        .fold(Array1::zeros(3), |acc, w, v| acc + w * v);
    weighted_sum
}
```

The issue I'm having is that I would expect the `.and(bar.rows())` to return `&ArrayView1<f32>` or even `&&ArrayView1<f32>`, but instead it's returning `ArrayView1<&f32>`. As far as I can tell, arithmetic operations aren't supported for containers of type `&f32`, so I'm a bit stuck. Why is `bar.rows()` returning borrowed values here?

**Comment by jturner314** [comment]
In the example code you've provided, the type of `w` is `&f32`, and the type of `v` is `ArrayView1<'_, f32>`. It turns out that arithmetic operations are not implemented for this particular combination of types. They are, however, implemented for `f32` and `&ArrayView1<'_, f32>` as the operands (among others).

So, one solution for this particular example is the following:

```rust
fn my_func(foo: &Array1<f32>, bar: &Array2<f32>) -> Array1<f32> {
    let weighted_sum = Zip::from(foo)
        .and(bar.rows())
        .fold(Array1::zeros(3), |acc, &w, v| acc + w * &v);
    weighted_sum
}
```

A list of arithmetic operator implementation is [provided here](https://docs.rs/ndarray/0.15.4/ndarray/struct.ArrayBase.html#arithmetic-operations). In this case, we can use the `K @ &A` implementation (where `K` is a scalar and `A` is an array). In order to use this implementation:

- I've added a `&` in front of the `w` in the closure parameters to dereference it, so that the `w` in the body has type `f32` (alternatively, you could leave the parameter alone, and add a `*` in front of the `w` in the closure body).
- I've added a `&` in front of the `v` in the closure body so that we have a reference to an array view (`&ArrayView1<'_, f32>`).

To answer the question at the end of your comment:

`bar.rows()` produces items of type `ArrayView1<'_, T>`. *Note that this is not the same thing as `ArrayView1<'_, &T>`.* A view consists of a pointer to the first element of the view, the shape of the view, and the strides of the view. You can think of it by analogy: `ArrayView<'a, T, D>` is to `Array<T, D>` as `&'a [T]` is to `Vec<T>`. The `.rows()` methods returns views instead of owned arrays, because returning owned arrays would require copying the data.

**Comment by zmitchell** [comment]
I have my arithmetic working now, thank you for that.

I'm still a little unclear on that generic type. With no prior knowledge I would expect the `X` in `ArrayView<'_, X>` to describe the type of elements that are in the array, e.g. an array of `&f32` in my original post. It sounds like this isn't the case though? Could you explain that a little more?

**Comment by jturner314** [comment]
Here's an example to illustrate what I mean by the element type of owned arrays and views:

```rust
use ndarray::prelude::*;

fn main() {
    // Owned array and array view with element type `f32`.
    let a1: Array1<f32> = array![1., 2.];
    let v1: ArrayView1<'_, f32> = a1.view();
    assert_eq!(a1, v1);
    
    // Owned array and array view with element type `&f32`.
    let a2: Array1<&f32> = array![&1., &2.];
    let v2: ArrayView1<'_, &f32> = a2.view();
    assert_eq!(a2, v2);
    
    // Neither of these compile, because the element types are different, and
    // `PartialEq<&f32>` is not implemented for `f32`.
    //assert_eq!(a1, a2);
    //assert_eq!(v1, v2);
}
```

> an array of `&f32` in my original post

Oh, I think I understand now where the confusion may be coming from. Here, I've added some type annotations to your original post and fixed the expression in the body of the closure to make it compile without errors:

```rust
fn my_func(foo: &Array1<f32>, bar: &Array2<f32>) -> Array1<f32> {
    let weighted_sum = Zip::from(foo)
        .and(bar.rows())
        .fold(Array1::zeros(3), |acc: Array1<f32>, w: &f32, v: ArrayView1<'_, f32>| -> Array1<f32> {
            acc + *w * &v
        });
    weighted_sum
}
```

My guess is that you're seeing that `w` has type `&f32`, which leads you to believe that the element type of `foo` is `&f32`. This conclusion is incorrect; `foo` is a reference to a 1-D array which contains `f32` elements; its type is `&Array1<f32>`. It is a "reference to a 1-D array containing elements which are `f32` values", not a "1-D array containing elements which are references to `f32` values".

This is analogous to the following example:

```rust
let v: Vec<f32> = vec![1., 2.];
let baz: &Vec<f32> = &v;
for item in baz {
    // ...
}
```

The `for` loop iterates over `baz`. `baz` is a reference to a `Vec` containing `f32` elements. `item` has type `&f32`, not `f32`. In other words, `item` is the type of the items produced by the iterator, which is not necessarily the same as the element type of the container.

In general, if you have a reference to a container with elements of type `T`, i.e. `&Container<T>`, it can only return items of type `&T`, unless the container clones elements to create the items.

Does that answer your question?

**Comment by zmitchell** [comment]
This was helpful, thank you!
