### ISSUE TITLE
Inverse of split_complex?

### ISSUE THREAD

**Issue by JP-Ellis** [rust-ndarray/ndarray#1166]
I have recently started using the [`split_complex`](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.split_complex) function which has been of great help, but I was wondering whether there is a convenience function for constructing a complex array from the real and imaginary parts separately?

Currently, the best I can think of is to use something along the lines of

```rust
let re = array![1, 2, 3];
let im = array![10, 20, 30];
let complex = Array1::from_shape_fn(re.dim(), |i| Complex::new(re[i], im[i]));
```

I have noticed that the `split_complex` code seems extremely efficient and (I believe it) uses the fact that the `Complex<T>` type is itself akin to `[T; 2]`.  Might something similar be possible to construct an array more efficiently than through an iterator as above?

**Comment by nilgoyette** [comment]
That function doesn't exist. While one may be tempted to add it to ndarray, it won't be faster than what you coded above (`Zip` could maybe make it a little faster, but nothing crazy). The maintainers don't want to add short methods like those.

> split_complex code seems extremely efficient

Yes, it is. It's fast because it's "doing nothing".  It simply returns 2 views of your original array.

    pub fn split_complex(self) -> Complex<ArrayViewMut<'a, T, D>>;
                                          ^^^^^^^^^^^^

There's no trick like that to build an owned array, nor a view.
