### ISSUE TITLE
Why does unrolled_dot check for length when we already know that they will be the same length?

### ISSUE THREAD

**Issue by KarlWithK** [rust-ndarray/ndarray#1174]
Hello, I'm currently being bottlenecked by unrolled_dot, so I was wondering a few things about it.

In this commit we see that someone added a cmp to get the minimum length, however, this function is only ever used after we check for length(I checked) and only public within the crate.
https://github.com/rust-ndarray/ndarray/blob/77c62860af8da2266a439b3b711029fbc0a616df/src/numeric_util.rs#L71

Also, if anyone has any tips on how to make a dot faster please let me know!

currently it's my biggest roadblock: 
![image](https://user-images.githubusercontent.com/31679231/175848102-7a26852f-9d55-4929-bf1f-c6ce6e659216.png)

**Comment by bluss** [comment]
The length computation there ensures that the slicing happening next has its bounds check elided, so it pays for itself (this is from memory). It's of course possible that how the compiler understands the code has changed since it was written - that's something you could look closely into. If unrolled_dot is slow, look at its operation of arithmetic, not the small overheads at start/end IMO. What's the data input, shape, strides and does it generate autovectorized code for this case or not? (Look at perf annotate disassembly to know).

**Comment by KarlWithK** [comment]
Thank you!
