### ISSUE TITLE
Copy into another part of the same array

### ISSUE THREAD

**Issue by nilgoyette** [rust-ndarray/ndarray#1207]
I'm trying to optimize my generic [padding](https://github.com/imeka/ndarray-ndimage/blob/master/src/pad.rs#L148) function. It's working perfectly but I realized that NumPy is around 4x faster than my version on 'reflect', 'symmetric' and 'wrap' (what I call `ByIndices`) I studied what [NumPy](https://github.com/numpy/numpy/blob/main/numpy/lib/arraypad.py#L296) does; it's quite simple.

    padded = input image + pad_size
    copy input image in center
    for each axis
        left_slice = left part of padded that needs to be copied
        left_chunk = padded[left_slice]
        pad_area = left part of padded that needs to be modified
        padded[pad_area] = left_chunk

        Idem for right side

I tried coding this in Rust instead of zipping on lanes and iterating on elements. Without success. Of course, the problem is that I'm trying to read and mutate at the same time the `padded` var.

Yes, I'm aware that I can use [multi_slice_mut](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.multi_slice_mut) to get 2 non-intersecting slices. This would actually solve my problem, but:

> When slicing arrays with generic dimensionality, creating an instance of `SliceInfo` to pass to the multi-axis slicing methods like `.slice()` is awkward. In these cases, it’s usually more convenient to use [...] slice_each_axis_mut.

I agree. That's why I'm using `slice_each_axis_mut`. However, This function returns an `ArrayView`, not a `SliceInfo`, so I can't call `multi_slice_mut`.

So, here are my questions:
- How does one build a `SliceInfo` in a generic context? The doc says that it's "awkward"... ok, probably, but how?
- Maybe I'm not seeing something obvious. Are there other ways to do `arr[slice1].assign(arr[slice2])` or to do what NumPy does, in rust-ndarray?

**Comment by jturner314** [comment]
> * How does one build a `SliceInfo` in a generic context? The doc says that it's "awkward"... ok, probably, but how?

You can do so by:

1. Building a [`Vec<SliceInfoElem>`](https://docs.rs/ndarray/latest/ndarray/enum.SliceInfoElem.html) representing the indices you want to use.
2. Converting it into a `SliceInfo` with [`SliceInfo::<_, Din, Dout>::new(the_vec)`](https://docs.rs/ndarray/latest/ndarray/struct.SliceInfo.html#method.new).

IMO, that process is "awkward" because building the `Vec<SliceInfoElem>` can be verbose, depending on what the user is trying to do.

> * Maybe I'm not seeing something obvious. Are there other ways to do `arr[slice1].assign(arr[slice2])` or to do what NumPy does, in rust-ndarray?

You can use [`ArrayViewMut::split_at`](https://docs.rs/ndarray/0.15.6/ndarray/type.ArrayViewMut.html#method.split_at) to split an `ArrayViewMut` into two independent pieces along an axis. (You can split those pieces further with more `split_at` calls.) Then, you can assign one piece to another. As I understand it, that would be a good fit for your needs:

```
for each axis:
    let v = array.view_mut();
    let (part1, part2) = v.split_at(axis, index);
    ...
```

We really need to add `multi_slice_axis_mut/_move` methods (#836) to make this kind of thing easier, i.e. instead of requiring the user to call `split_at` multiple times. Those methods just haven't been implemented yet.

**Comment by nilgoyette** [comment]
> You can use [ArrayViewMut::split_at](https://docs.rs/ndarray/0.15.6/ndarray/type.ArrayViewMut.html#method.split_at) to split an ArrayViewMut

Nice, this is perfect for my use-case, thank you! I'm using a mix of `split_at` and `slice_each_axis_mut`. I'll test the double `split_at` later.

Turns out my performance problem is elsewhere (copying the input into `padded`) but at least the code is clearer now :)
