### ISSUE TITLE
Row/column-wise Zipping?

### ISSUE THREAD

**Issue by librarianmage** [rust-ndarray/ndarray#1244]
Hello, I was wondering if there was a way to do a Zip that worked with rows/columns. I have some operations that I want to use that transform the entire axis at once (in this case, a scan across the row), but using array.rows() in the zip just makes it a one-dimensional array that contains arrays.

**Comment by nilgoyette** [comment]
I'm not sure I understand your question, but I think you're asking for [fold_axis](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.fold_axis). If not, please be clearer.

**Comment by librarianmage** [comment]
I am looking for a function, that when passed arrays of equal dimensions,
concatenates them back into an array along the same axis. For instance, I
would be able to iterate over each row of a 2d array, sort the values, and
then end up with a 2d array whose rows consist of sorted values.

Can fold_axis do that? I’m not quite sure how I’d get it to do that.

**Comment by nilgoyette** [comment]
Then you should be able to use [concatenate!](https://docs.rs/ndarray/latest/ndarray/macro.concatenate.html) for the first part. Then you can iterate on the rows of this newly-created array. However, I probably still misunderstand your question because I don't see where you need to zip anything here. You can give an actual toy example (like, 2x3 arrays) to be sure everybody understand your problem.

If you actually want to sort numbers in a ndarray, you will need [as_slice_memory_order_mut](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.as_slice_memory_order_mut) because the Rust tools to sort only accept slices. This should work for rows. For columns, you will need an array in 'f' order to have contiguous memory in the "column" direction. Sorry, this is somewhat complex; this is because you asked to sort instead of any random mathematical operations!

**Comment by librarianmage** [comment]
Ok, then I will be cleaner with my personal use case :sweat_smile: (Spoilers for Advent of Code Day 8 ahead)

One way to to solve the first part is to slide across each row of the 2D grid provided (well, direction—left-to-right, top-to-bottom, right-to-left, bottom-to-top, but the rest of the cases can be dealt with slicing and transposition). The way I ended up doing it is
```rust
type HeightGrid<T> = Array<T, Ix2>;
type HeightGridView<'a, T> = ArrayView<'a, T, Ix2>;

fn max_height(
    heights: HeightGridView<i8>,
) -> HeightGrid<i8> {
    Array::from_shape_vec(
        heights.dim(),
        heights
            .rows()
            .into_iter()
            .flat_map(|r| r.into_iter().scan(-1, max_height_axis))
            .collect(),
    )
    .unwrap()
}
```

which really contorted. What I want to do is zip them axis-wise so I can do an axis-based operation (an operation that requires information about the rest of the axis) and end up with something in the same dimension.

**Comment by librarianmage** [comment]
The reason I tried zipping was how to go with it because the documentation states
> Using [Zip](https://docs.rs/ndarray/latest/ndarray/struct.Zip.html) is the most general way to apply a procedure across one or several arrays or *producers*.

**Comment by librarianmage** [comment]
As for in-place mapping, the second part had me go from an array of `i8`s to an array of `usize`s

**Comment by nilgoyette** [comment]
Hum, if I had to code it, I think I would code it that way

    let mut ans = Array::zeros(heights.dim());
    Zip::from(ans.rows_mut()).and(heights.rows()).for_each(|ans, heights| {
        // Would be super nice to have a single short line here... I'm not sure how.
        for (o, &i) in ans.iter().zip(heights.into_iter().scan(-1, max_height_axis)) {
            *o = i;
        }
    });
    ans

Still not terribly sexy, but we removed the unwrap :)

**Comment by librarianmage** [comment]
Is there a way to assign over a mutable slice? 🤔

**Comment by nilgoyette** [comment]
Well, yes, but as my last edit suggested, you can only assign from another ndarray (or from a Vec if you create an ArrayView before), not from an iterator.

**Comment by librarianmage** [comment]
ah I missed second part, apologies
