### ISSUE TITLE
Is there any alternatives than this lib in rust? It's too hard than numpy to use

### ISSUE THREAD

**Issue by lucasjinreal** [rust-ndarray/ndarray#1245]
For instance, How can I using the base type in a function?

```rust

fn test_gemm(a: ArrayBase, b: Array) {
    let mut a = Array::range(0, 12, 2).into_shape([3, 4]).unwrap();
}

```

In numpy, we just make type as ndarray, but rust how to do it? what's the base type? Ddoes it Array2<_, f>?  how about users send Array3? Why not just NDArray?

**Comment by ttencate** [comment]
If your function can handle arrays of different dimensions and/or data types, you need to make the function itself generic.

```
fn test<A, D>(a: Array<A, D>)
    where D: Dimension
{
    ...
}
```

This is a basic Rust principle, which helps guarantee correctness at compile time, rather than crashing at runtime like numpy would if the dimensions and/or data types don't match.

**Comment by jinfagang** [comment]
Also, how to print the shape when the type is arbitry

<img width="534" alt="image" src="https://user-images.githubusercontent.com/21303438/208124771-f0d510f7-8747-4e64-975d-796bd1b84529.png">

**Comment by ttencate** [comment]
I suggest you learn the basics of Rust first, such as references, mutability and how to use format strings.

**Comment by jinfagang** [comment]
@ttencate Hi, thank u, I know how to format, but in this generic way compile complains it can not format
