### ISSUE TITLE
What would be the equivalent of numpy's `dtype` in `ndarray`?

### ISSUE THREAD

**Issue by nbro** [rust-ndarray/ndarray#1251]
Rust is, of course, statically and strongly typed. However, I wonder if it would make sense to have something like `dtype` for arrays in ndarray. I am not a Rust expert too, but it seems that there's a way to query the type of a variable. See [this SO post](https://stackoverflow.com/q/21747136/3924118). This could be useful because Rust has multiple integer and float types and one may need to know which specific type do the elements of an array have at runtime. This would just be a nice-to-have feature. Have you ever thought about this?

**Comment by LazaroHurtado** [comment]
By `dtype` do you mean at array creation time, aka `np.array([1,2,3], dtype=float)`? Or the field, aka `arr.dtype` where `arr` is a numpy array?

If its the first one then ndarray already has this feature, for example the `ArrayBase` struct requires two generics, one for the type and the other for the dimension.

If its the second one then I'm not too sure. I don't think its natural/clean to branch depending on a variables type. If the goal is to create an array `b` with a similar type as array `a` then it can be done using generics:
```
fn copy_array_type<A: Clone + Zero, D>(a: Array<A, D>) -> Array2<A> {
    Array2::<A>::zeros((2,2))
}
```
Can you give an example of when its a must to know the array type at runtime? I'm probably overlooking a good scenario

**Comment by adamreichold** [comment]
> So, it seems that we need to pass a `FixedInitializer`.

One can leave out types which can be inferred, e.g.

```rust
let a = arr2::<f32, _>(&[[10, 7, 23]]);
```

but more generally specifying the element type when the elements are given is usually not helpful as Rust does not do implicit conversions of numerical types, i.e. the above will never compile due to

```
error[[E0271]](https://doc.rust-lang.org/stable/error-index.html#E0271): type mismatch resolving `<[{integer}; 3] as FixedInitializer>::Elem == f32`
```

i.e. the literals given will always correspond to an integer type and more idiomatic version making an explicit choice would be to change the literals, e.g.

```rust
let a = arr2(&[[10.0_f32, 7., 23.]]); 
```

More generally, I suspect the original issue is related to a lack of experience with using this crate. The equivalent of NumPy's `dtype` is the generic type argument, e.g. the `A` in

```rust
Array<A, D> = ArrayBase<OwnedRepr<A>, D>
```

and everywhere one needs to mention that element type, e.g. in generic functions and their where clauses, it is bounds to a generic type argument or accessible as an associated type like `Elem` in

```rust
<S as RawData>::Elem
```

given

```rust
ArrayBase<S, D>
```

If you want to learn more about how the dynamically typed internals of NumPy and the statically typed approach of ndarray can be matched, you can have a look at the [rust-numpy](https://github.com/pyO3/rust-numpy) crate.

**Comment by adamreichold** [comment]
> This would only improve the usability of the crate because people would need to write less code.

Writing array literals is _not_ a commonly used technique in the code bases that I know of, hence I would argue against complicating it with the question of how to model numerical conversions (c.f. the [num-traits](https://docs.rs/num-traits/latest/num_traits/) crate on how complicated this actually is). This seems especially so as modifying the literal values themselves to have the target type is simple enough, e.g.

```rust
let a = arr2(&[[10_u16, 7, 23]]);
```

is actually simpler IMHO.

**Comment by LazaroHurtado** [comment]
I agree with @adamreichold that it might just be simpler to specify the target type. Nonetheless I was interested in seeing how your idea would work out so I wrote some [small code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1cb38d217b74a3987b86b08867020b7d) to see how it could be done:
```
fn arr2_typed<T, A: Clone + Into<T>, const N: usize>(elems: &[[A; N]]) -> Array2<T> {
    let n = elems.len();
    let all_elems = elems.to_vec().into_iter().flatten();
    let converted_elems = all_elems.map(|elem| elem.into()).collect::<Vec<T>>();
    let m = converted_elems.len() / n;
    Array::from_shape_vec((n, m), converted_elems).unwrap()
}

fn main() {
let a: Array2<f32> = arr2_typed(&[[1i16, 2],[3, 4]]);
println!("{:?}", a);
}
```
This should achieve what you mentioned but there are somethings to notice here. First off, this snippet is similar to how `arr2` is [implemented](https://docs.rs/ndarray/latest/src/ndarray/free_functions.rs.html#213-218) but with an extra generic that will be used to specify to desired type. Also notice how I had to specify a type within the array literal due to i32 (default type) not implementing Into\<f32\>, which is the type of `Array2`. Finally, I also had to use `Array::from_shape_vec` instead of `Array2::from` because `converted_elems` is a `Vec` which is not a `FixedInitializer` (maybe you can make it work!).

Using this code would require the end user to either specify the type for every variable or explicitly defined every generic, i.e `let a = arr2_types::<f32, i16, 2>(&[[1, 2], [3, 4]])`. Both of which is too much friction imo but there might be uses cases where it is necessary.
