### ISSUE TITLE
Equivalent to `numpy.gradient` for a 1D/2D array?

### ISSUE THREAD

**Issue by Nevsden** [rust-ndarray/ndarray#1267]
Is there an equivalent to the numpy function for automatic gradient computation on a 1D or 2D array?

**Comment by bytesnake** [comment]
There is no autodiff capability implemented for ndarray and it is unlikely that it will be in the future. Take a look to https://github.com/burn-rs/burn or https://github.com/coreylowman/dfdx

**Comment by nilgoyette** [comment]
Hi @Nevsden.  I added a 2D `gradient` function into my private codebase. It's not the exact same thing because I needed to use `nalgebra Point`, but you should be able to adapt it.

    pub fn gradient<T>(a: &[Point3<T>]) -> Vec<Point3<T>>
    where
        T: Copy + RealField,
    {
        let n = a.len();
        let h = T::from_subset(&(2.0));

        let mut out = Vec::with_capacity(n);
        out.push(Point3::from(a[1] - a[0]));
        for i in 0..n - 2 {
            out.push(Point3::from((a[i + 2] - a[i]) / h));
        }
        out.push(Point3::from(a[n - 1] - a[n - 2]));
        out
    }

If you need something else the Mx3, you can check the [NumPy code](https://github.com/numpy/numpy/blob/v1.24.0/numpy/lib/function_base.py#L970-L1313).

I'm closing this issue. Even if someone were to contribute it, it would be added into the ndarray ecosystem, not into ndarray.
