### ISSUE TITLE
alternative methods of collecting an axis_iter to ndarray matrix

### ISSUE THREAD

**Issue by kernelmachine** [rust-ndarray/ndarray#249]
I'm working on a dataframe implementation that provides two-dimensional iterator adaptors over ndarray matrices. 

```
pub struct DataFrame {
    pub columns: Vec<OuterType>,
    pub data: Matrix<InnerType>,
    pub index: Vec<OuterType>,
}
```

The dataframe's data are an enum over something called `InnerType`, which allows the dataframe to support a variety of types, like dataframes in other languages:

```
pub enum InnerType {
    Float(f64),
    Int64(i64),
    Int32(i32),
    Str(String),
    Empty,
}
```

The iterator adaptors `impl Iterator<Item = (OuterType, ArrayView<'a, InnerType, usize>)>`.

Notice the `InnerType::Str(String)`. Because of this value, `InnerType` is not Copy, and I'm unable to collect the adaptors' items into a DataFrame via `stack`. Can you help me think of another way to collect the iterator adaptor into an ndarray matrix, without needing Copy, so I can support Strings in the dataframe? This problem may also affect implementing something like `FromCSV`, which would go from a CSV reader iterator to a DataFrame.

If you want to check out the project further, you can do so here: https://github.com/pegasos1/rust-dataframe

**Comment by bluss** [comment]
stack could probably support it, it's just a lot more work to do non-Copy (Copy => no destructor, no ownership semantics). The unknown factor is if there's a perf loss with the new implementation.

**Comment by pegasos1** [comment]
IIRC stack preallocates and then uses `assign`. What methods can we use for a move?

**Comment by pegasos1** [comment]
Also yes, I think it warrants testing, but I'm not sure if the original function should be reimplemented. Any perf loss by using non-Copy is probably only worth it for specific use cases like mine. In that case, maybe we should have a totally new non-Copy stack function.

**Comment by bluss** [comment]
Extending an array is not cheap in general (due to flexible memory layout) so for a new stack I would consider writing the operation using `Vec::extend` and only making a Vec out of the data at the end of the operation.

**Comment by bluss** [comment]
I'd really recommend to somehow use the native types as the array element type. I.e use an array of f64, not an array of item type. That lifts the item type enum up to be around the array. It's probably not as neat to write, but it is a whole lot more efficient for numerical operations.

**Comment by pegasos1** [comment]
Yeah I’ve thought about that. I think I’m going to create separate DataFrame structs depending on whether you know your element types are uniform. 

Suchin Gururangan

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Wed, Dec 14, 2016 at 2:58 PM bluss

<
mailto:bluss <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I'd really recommend to somehow use the native types as the array element type. I.e use an array of f64, not an array of item type. That lifts the item type enum up to be around the array. It's probably not as neat to write, but it is a whole lot more efficient for numerical operations.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/bluss/rust-ndarray/issues/249#issuecomment-267183624
, or

**Comment by bluss** [comment]
Oh, I didn't think about that, sorry. I've been thinking that a data frame would fix each "column" to a particular type.

**Comment by pegasos1** [comment]
Oh oh oh I totally misread your original point — I read “array” as “matrix". You were talking about columns.

Your point is totally valid, I should lift the InnerType to the column level, as column types are fixed. That may change how the library handles missing values, though.

Suchin Gururangan

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Wed, Dec 14, 2016 at 4:30 PM bluss

<
mailto:bluss <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Oh, I didn't think about that, sorry. I've been thinking that a data frame would fix each "column" to a particular type.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/bluss/rust-ndarray/issues/249#issuecomment-267200384
, or

**Comment by bluss** [comment]
parallelization of `.map() -> Array` (as "par_map", not yet merged) touched upon this kind of thing.

**Comment by bluss** [comment]
Have you seen this? Might be a good resource for ideas

http://wesmckinney.com/blog/a-roadmap-for-rich-scientific-data-structures-in-python/

**Comment by SuperFluffy** [comment]
In the [discussion on reddit](https://www.reddit.com/r/rust/comments/5ks00y/introducing_utah_a_rust_dataframe/) about the [Utah dataframe library](https://github.com/pegasos1/utah) for Rust, the [Pandas 2.0 rewrite](https://pandas-dev.github.io/pandas2/) was mentioned. Looks like Pandas is suffering form performance issues because of the way they chose to implement their original datastructures.

Maybe good to keep in mind. :-)

**Comment by bluss** [comment]
That is indeed the same library that @pegasos1 started this issue with. I hadn't seen the reddit post though, so thanks for the link.

**Comment by pegasos1** [comment]
Yeah, both utah and pandas suffer from copies. However, in utah the copies are only necessary because the iterator needs to own the elements it returns. I think building the dataframe around streaming iterators would solve the issue, but haven't gotten around to looking into it yet. @bluss i've seen traces of your thoughts on streaming iterators on various forums.

**Comment by bluss** [comment]
Also http://www.jeffreytratner.com/slides/pandas-under-the-hood-pydata-seattle-2015.pdf for internals

**Comment by bluss** [comment]
Is this still an issue? We need to formulate the solution here.

**Comment by bluss** [comment]
Stack and append support Clone elements (from ndarray 0.15.2), #932
