### ISSUE TITLE
Support `Clone` elements in `stack` and `select`

### ISSUE THREAD

**Issue by bluss** [rust-ndarray/ndarray#269]
Related issue to #249

**Comment by jturner314** [comment]
This also applies to the `.select()` method (which is implemented in terms of `stack`).

**Comment by jturner314** [comment]
To avoid uninitialized data issues, probably the simplest implementation would be to choose the iteration order and memory layout such that a `Vec` could be extended with the data from each array in sequence, and then re-interpret the `Vec` as an `Array` at the end.

For example, let's say you want to stack arrays `a` and `b` along axis `2`. I think this will work:

1. Permute the axes of `a` and `b` to move axis `2` to be the first axis, but preserve the ordering of the other axes.
2. Create a new `Vec`.
3. Extend the `Vec` from `a.iter().cloned()`, and then extend it with `b.iter().cloned()`.
4. Convert the `Vec` into an `Array`. (The first axis of this array will correspond to axis `2` of `a` and `b`, and the other axes will be in order.)
5. Permute the axes of the `Array` to move the first axis to be axis `2`.

This approach isn't necessarily the fastest because the iteration order may not be ideal, but it's relatively straightforward and doesn't need any `unsafe` code.

**Comment by gussmith23** [comment]
Wondering if there's any movement on this -- I think this is blocking me. I'm using ndarray to hold tensors of non-"simple" values (i.e. things that don't implement `Copy`, like other tensors!). I know that use-case probably raises hairs on some peoples' necks, but `ndarray` has been handling it pretty well up til now! It would be a bummer if this turned out to be a permanent block.

**Comment by gussmith23** [comment]
Also FWIW, I could take a crack at implementing something!

**Comment by bluss** [comment]
Let's get the #735 merged first (or base the work on that).

Non-copy elements aren't all that simple, but jturner has a plan here, and it sounds like it's a good one https://github.com/rust-ndarray/ndarray/pull/797#issuecomment-615824117
