### ISSUE TITLE
Writing raw bytes &[u8] from ndarray to child stdin

### ISSUE THREAD

**Issue by jimbo1qaz** [rust-ndarray/ndarray#524]
I'm new to Rust and trying to port a program I wrote in Python, which uses Matplotlib (too slow) to generate `bytes` objects, written into a subprocess pipe.

Numpy ndarray supports conversion to bytes (https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tobytes.html ).

I'm thinking of writing a quick-and-dirty line-drawing library (also too slow in Python), which loops over Rust `Array::<u8,_>`. (https://github.com/coder543/dataplotlib seems inactive). However I don't know how to pull raw bytes out of a ndarray to write to a ChildStdin.

AFAIK https://docs.rs/ndarray/0.12.0/ndarray/struct.ArrayBase.html doesn't mention `bytes` or `u8`.

https://doc.rust-lang.org/std/process/struct.ChildStdin.html and https://doc.rust-lang.org/std/io/trait.Write.html apparently only take `&[u8]`.

https://github.com/rust-ndarray/ndarray/pull/345/files ???

should I just research Nim/etc. instead?

**Comment by jimbo1qaz** [comment]
Found a solution: https://docs.rs/ndarray/0.10.7/ndarray/struct.ArrayBase.html#method.as_slice etc.

```rust
let white = Array::<u8,_>::from_elem((1280,720,3), 255);
let white_s = white.as_slice().expect("oops");
```

Should this be made more clear in the documentation? I spent over 20 minutes looking for it.
- Ctrl+F `slice` returned mostly methods (including `slice()` returning `ArrayView<A, Do>` instead of slice objects.
- Ctrl+F `&[` returned mostly hardcoded input data, instead of returning slice objects.
- Ctrl+F `&[u8` returned nothing.
- Is there any IDE that would've made finding the needle in the haystack easier?

**Comment by jturner314** [comment]
I've submitted a PR (#527) to add a table of conversions to/from `Vec`s and slices.

When looking for a relevant method, I often find it helpful to use the left sidebar of the docs, which has a compact listing of all of the available methods and trait implementations. (Even though there are quite a few methods, it doesn't take very long to scan the list for method names that might be relevant since there's no clutter to skip over.) You can also use the [+] and [-] buttons to expand/shrink sections. When the details are shrunk, the result is a compact listing that includes the parameter and return types.

**Comment by jturner314** [comment]
#527 has been merged. Closing this issue.
