### ISSUE TITLE
Make ndarray-parallel a direct optional part of ndarray?

### ISSUE THREAD

**Issue by bluss** [rust-ndarray/ndarray#551]
Rayon is now 1.0 and the plumbing parts we use to implement parallel iterators are as stable as the rest of the crate. See that written in this PR: https://github.com/rayon-rs/rayon/pull/469

Rayon plumbing docs: https://docs.rs/rayon/*/rayon/iter/plumbing/index.html

This makes it viable to make rayon a direct dependency of ndarray, presumably an optional one, and it lets us simplify its usage.

**Comment by LukeMathWalker** [comment]
It would be great to have all methods that could benefit from parallelization to use it out of the box with `rayon` as a direct dependency. 
But given that you mention that it might be better to put it behind a feature flag (thus retaining a separate `par_` version for all those methods I assume) I wanted to ask: what are the drawbacks? Are there significant reasons that might lead someone not to use `ndarray` because of a non-optional dependency on `rayon`? 
Genuine curiosity :)

**Comment by bluss** [comment]
Sure, I wouldn't use it if I couldn't deselect features I wasn't using.

clean build of ndarray: 22 sec
clean build of ndarray + rayon: 41 sec

on a hot slow laptop

**Comment by LukeMathWalker** [comment]
`Array::map` and iterators, as well as all the functions and methods using those under the covers.
But yes, introducing `Send` and `Sync` bounds everywhere is damaging.

**Comment by bluss** [comment]
Once upon a time in nightly you could *specialize* on presence or absence of Send/Sync and parallelize as allowed. Not even sure that's a good idea, but it's pretty cool. At the moment we don't know when/if specialization will arrive though.

**Comment by LukeMathWalker** [comment]
We could approach the problem from a different perspective: `map` and related functionalities (`mapv`, `*_inplace`, etc.) could be moved out of the default struct implementation and be provided in a trait (`Mappable`?); we could the provide another trait (`ParMappable`?) behind a feature gate that uses exactly the same names for methods but requires `Send`+`Sync` to use `rayon` and make them parallel by default.

If the `rayon` feature gate is off, then `Mappable` is in the prelude, otherwise we put `ParMappable` in the prelude. In this way a user can still use both types of methods if necessary by explictly importing the `Mappable` trait with the rayon feature flag on.
What do you think?

**Comment by bluss** [comment]
It doesn't match the "feature flags are purely additive" rule which we need as soon as there is more than one crate that uses ndarray in the currently compiling project. What happens is that one crate can pull in ParMappable without the other crate being ready for it.

**Comment by bluss** [comment]
Let's work on making the parallel methods visible. I think that in general we don't want this to happen automatically, the users will know which operations to parallelize. That said there could certainly be ways we can make it easier to opt in to this -- even a newtype, a wrapper type?

ndarray-parallel is also missing some important operations, most notably `.map()`! It only has in place mappings. With the code in the main crate and more visible, this can get some attention.

**Comment by bluss** [comment]
Hrm, the LinalgScalar trait doesn't have the foresight of requiring `Send + Sync`, but it does require `'static` which allows ad hoc type dispatch. So we can parallelize linalg methods for specific scalar types (like primitive numeric types) transparently.
