### ISSUE TITLE
Forward more iterator methods for element iterators

### ISSUE THREAD

**Issue by bluss** [rust-ndarray/ndarray#555]
The `Iter` and `IterMut` are composed of a contiguous case and a general case, and because of this we should forward most (non-adaptor) methods to the underlying iterators. The existing `fold` and `rfold` methods serve as examples. No new custom implementations of the methods are needed in ElementsBase or Baseiter.

The ultimate ones to forward are `try_fold` and `try_rfold`, but they need to wait for having stable signatures (all traits in the signature).

Good ones to forward:

- nth
- collect
- all, any
- find, find_map

Some don't matter because they use fold that we already forward: count, max, min, max_by etc, sum, product

**Comment by andrei-papou** [comment]
Hi @bluss . I'd like to pick this one up.

**Comment by jturner314** [comment]
@andrei-papou That would be great.

Regarding with methods to forward, @bluss has provided some good suggestions. If you'd like to investigate yourself, I recommend looking at [the methods `std::slice::Iter` overrides](https://github.com/rust-lang/rust/blob/1.33.0/src/libcore/slice/mod.rs#L2828-L3006) and, since we can't yet forward `try_fold` and `try_rfold`, the methods of [`Iterator`](https://github.com/rust-lang/rust/blob/1.33.0/src/libcore/iter/iterator.rs#L92-L2608) and [`DoubleEndedIterator`](https://github.com/rust-lang/rust/blob/1.33.0/src/libcore/iter/traits.rs#L390-L639) that are implemented in terms of `try_fold` and `try_rfold`.
