### ISSUE TITLE
Copy bound in uninitialized()?

### ISSUE THREAD

**Issue by aldanor** [rust-ndarray/ndarray#568]
Wondering how much `Copy` bound is really needed in `uninitialized()`, and could it be lifted? (would be nice to have in cases when you know what you're doing... or don't mind shooting yourself in the foot a little bit)

https://github.com/rust-ndarray/ndarray/blob/1b1a5035b25cf831923853b72b075cc3d988e2c5/src/impl_constructors.rs#L364-L368

**Comment by jturner314** [comment]
We need to keep the `Copy` bound because it would be extremely easy to cause undefined behavior without that bound. The purpose of the `Copy` bound is to prohibit using `uninitialized` with element types that implement `Drop`. The primary issues with uninitialized elements of a type that implements `Drop` are

1. It's undefined behavior if the array is dropped before all the elements are initialized. This also implies that the user must ensure that nothing panics before all the elements are initialized.
2. Normal assignment to an uninitialized element is undefined behavior, so calling a method like [`.fill()`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.fill) or just doing something like `arr[(1, 2)] = value` is undefined behavior.

See the docs of [`std::mem::uninitialized`](https://doc.rust-lang.org/std/mem/fn.uninitialized.html), and in particular the example, for details.

If you *really* want to get an uninitialized `Array` of a non-`Copy` type, you can create an uninitialized `Vec` (using `Vec::with_capacity` and `set_len`) and then convert it into an `Array` with [`from_shape_vec`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.from_shape_vec)/[`from_shape_vec_unchecked`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.from_shape_vec_unchecked). I *strongly* recommend against doing this, though; it's just too easy to mess up.

In the future, once [`MaybeUninit`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html) is stabilized, we'll have a better way to handle uninitialized data. Additionally, current `master` branch of `ndarray` (not released yet) has a `RawArrayViewMut` type that would be helpful for dealing with uninitialized data. Until either of those is available, though, I strongly recommend that you initialize any non-`Copy` data.

**Comment by aldanor** [comment]
@jturner314 I see, thanks!
