### ISSUE TITLE
Return slice, &[T], containing all elements of any array type (continuous and non-continuous)

### ISSUE THREAD

**Issue by SuperFluffy** [rust-ndarray/ndarray#572]
To interact with Blas wrappers, it sometimes nice to use a rust slice together with the n-dimensional stride of the containing array type.

As it stands right now, `ArrayBase::as_slice` and related methods only return slices if the underlying structure is continuous. However, some Blas methods allow you to specify strides together with a pointer to allow you to index into a slice and pick the correct elements.

For example, assume I have a row-major matrix and I want to pick the `i`-th column and construct a slice from it, then right now I have to do the following operations:

```rust
let n_rows = 5;
let n_cols = 5;
let a = Array2::ones((n_rows, n_cols));
let i = 2;
let first_elem = a.column(i).as_ptr();
let col_slice = std::slice::from_raw_parts(first_elem, a.len() - (n_cols - 1));
```

`col_slice` is hence a slice that contains all elements of the the `i`-th column, with `col_slice[0]` and `col_slice[col_slice.len()]` being the first and last element of the column, respectively.

## Proposal

I propose to include a method that returns a rust slice `&[T]` (not a slice in the `ndarray` sense) that spans all elements of any array type, be it continuous or not. Together with `ArrayBase::strides` the user can then manually index the underlying slice and get the required elements. This is one step lower than working on the level of ndarray, yet prevents one from going all the way down to pointer level.

This also makes it easier to stay on the level of wrappers around blas and lapack without having to wrangle with ffi and casting to `c_int` and the like.

This is not completely fleshed out, but it could look something like this:

```rust
fn as_rust_slice<S, T, D>(a: &ArrayBase<S, D>) -> &[T]
    where S: Data<Elem=T>,
          D: Dimension
{
    let len = a.len();
    let strides = a.strides();
    let total_slice_len = strides.into_iter().fold(len, |a, b| a * b);
    let a_ptr = a.as_ptr();
    std::slice::from_raw_parts(a_ptr, total_slice_len)
}

fn as_rust_slice_mut<S, T, D>(a: &mut ArrayBase<S, D>) -> &mut [T]
    where S: DataMut<Elem=T>,
          D: Dimension
{
    let len = a.len();
    let strides = a.strides();
    let total_slice_len = strides.into_iter().fold(len, |a, b| a * b);
    let a_ptr = a.as_mut_ptr();
    std::slice::from_raw_parts_mut(a_ptr, total_slice_len)
}
```

Any opinions on this? It would be quite useful for me, but maybe the use case is too specific. If you give me the go ahead, @jturner314 and @bluss, then I can make a PR.

**Comment by bluss** [comment]
For ArrayViews this is not sound because they only borrow the actual elements they expose, and any other array view (mut or shared) can at the same time borrow a disjoint piece of the array, but where the raw data slices like you define them here, overlap.

For example, the columns of a row major matrix. Let's say we have a mutable array view of column 0 and read-only array views of column 1 and 2. We can't allow array views of columns 1 and 2 to extract such data slices.

For owned arrays, this could in principle be done but locks us in API wise, in regard to how we handle elements that are not in the current view/slicing of the owned array. They could in the future be uninitialized or moved-from or dropped.

A one-dimensional array view/mut is already exactly a raw pointer, the length and the stride, so it's a good datatype for transporting this information. If you decide to convert these to slices you can do that, but your unsafe code needs to make sure you're not creating slices that overlap with someone's mutably borrowed elements. Isn't there a way you can carry these pieces of information further as just array views, and convert to pointer, len, stride down the line? Or other raw / unsafe access API that would help?

**Comment by jturner314** [comment]
The proposed feature cannot be implemented in a sound way, and there hasn't been any discussion for a few months, so I'm closing this issue. If there's some other related feature that would be useful, please feel free to open a new issue.
