### ISSUE TITLE
Is the project still in development ?

### ISSUE THREAD

**Issue by Ricocotam** [rust-ndarray/ndarray#594]
All is in the title. I see issues and PR but nothing has been committed since December.

I'd like to use this crate but I don't want to rely on something not being maintained. I'd be sad if such a great project is not pursued.

Best of all

**Comment by LukeMathWalker** [comment]
It definitely is @Ricocotam! Some PRs are ready but include breaking changes (like #580) so they might be merged after a bunch of other PRs that do not include breaking changes (like #593, #591, #588) in order to cut a patch release (`0.12.2`) before a new major release (`0.13.0`).
A bunch of PRs are waiting for a second reviewer, but the project is definitely alive.

There is a whole ecosystem of crates building on top of it ([`ndarray-stats`](https://github.com/jturner314/ndarray-stats), [`ndarray-linalg`](https://github.com/termoshtt/ndarray-linalg), [`linxal`](https://github.com/masonium/linxal), [`ndarray-vision`](https://github.com/xd009642/ndarray-vision),  [ecc](https://crates.io/search?q=ndarray)), both new and old ones, hence I wouldn't doubt the investment of the scientific Rust community in `ndarray`.

**Comment by Ricocotam** [comment]
Awesome, super glad to hear this. Does any tutorial/docs has been released ? I didn't search but I didn't find it on the readme

**Comment by LukeMathWalker** [comment]
All Rust crates have their docs automatically built and uploaded on [https://docs.rs/](https://docs.rs/) once they are released on [crates.io](https://crates.io).

Depending on your background, this particular section might turn out to be quite useful: [ndarray for NumPy's users](https://docs.rs/ndarray/0.12.1/ndarray/doc/ndarray_for_numpy_users/index.html).

I am also putting a together a long-form tutorial - still early days, but you can find the first post (on `Vec<T>`) [here](https://www.lpalmieri.com/posts/2019-02-23-scientific-computing-a-rust-adventure-part-0-vectors/).
