### ISSUE TITLE
Serde: more helpful error when it fails deserialize

### ISSUE THREAD

**Issue by Ploppz** [rust-ndarray/ndarray#595]
I tried to deserialize a struct that contains a `Vec<Array1<f64>>` and a `Vec<Array2<f64>>`, from data that was serialized from another type... obviously this should fail. I got the error message `"unknown array version: 12"`, and failed to see that I was deserializing the wrong struct. The error message is of course garbage because I had garbage input. So maybe the Deserialize implementation on `ArrayBase` should somehow check that what it tries to serialize is in fact an `ArrayBase`, like a magic header?
I was using bincode.

**Comment by jturner314** [comment]
Hmm... I don't know about this. I'd like to be consistent with the rest of the `serde` ecosystem; if we deviate, we should have a good justification (what makes `ArrayBase` special?). Do any other types use a magic header? I don't think a typical `derive`-generated implementation does. The [`ArrayBase` implementation](https://github.com/rust-ndarray/ndarray/blob/master/src/array_serde.rs) pretty much follows [the example in the serde docs](https://serde.rs/deserialize-struct.html).

With bincode you definitely have to know the correct type ahead-of-time, since AFAIK it doesn't even include delimiters like you'd get with JSON or similar.

**Comment by Ploppz** [comment]
Yeah, you are right. I suppose it's up to the format to do this.
