### ISSUE TITLE
Question on performance on vector operation

### ISSUE THREAD

**Issue by jdmichaud** [rust-ndarray/ndarray#677]
I am trying to perform vector operations (multiply-add). This example below is using ndarray (never mind that what it actually does is useless):
```
#[macro_use(array)]

extern crate ndarray;
use std::time::Instant;

fn main() {
  let buffer = vec![0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0];
  let a = array![0.0, 0.0];
  let u = array![1.0, 0.0];
  let v = array![0.0, 1.0];
  let step_x = 3.0 / 512.0;
  let step_y = 3.0 / 512.0;
  let mut sum = 0f32;

  let now = Instant::now();
  for j in 1..512 {
    for i in 1..512 {
      // let x = a[0] + u[0] * (step_x * i as f32) + v[0] * (step_y * j as f32);
      // let y = a[1] + u[1] * (step_x * i as f32) + v[1] * (step_y * j as f32);
      // sum += buffer[(y.floor() * 3.0f32 + x.floor()) as usize];
      let x = &a + &(&u * (step_x * i as f32)) + &(&v * (step_y * j as f32));
      sum += buffer[(x[1].floor() * 3.0f32 + x[0].floor()) as usize];
    }
  }
  println!("sum {:?}", sum);
  println!("{:?} ms", now.elapsed().as_nanos() as f64 / 1_000_000f64);
}
```

So I am scaling two vectors and then adding to another vector and storing this into a result variable. This takes around 115ms on my machine. Doing the same thing with the commented code, takes around 2ms.

My undestanding is that, in the ndarray operation, an ndarray is allocated, at each loop. That's why it is way slower. What would I do if I wanted my code to remain easier to understand by using ndarray operation but be faster? I tried to allocate an array on the stack before the loop, consuming it in the operation and reinitialize it at the end of the loop. I gain around 35ms but this is still too slow.

Any idea how to perform those types of operation efficiently?

**Comment by LukeMathWalker** [comment]
Hi @jdmichaud!

I don't have a computer right now to reproduce and time the two versions locally. Would you mind providing a flamegraph so that we can analyze where both versions are spending their time? (See https://ngoldbaum.github.io/posts/python-vs-rust-nn/ as an example)

**Comment by jdmichaud** [comment]
![flamegraph](https://user-images.githubusercontent.com/11454727/62230729-b8627b80-b3c2-11e9-9931-dd379d1b75d8.jpg)

Its not really readable but github doesn't accept svg. It confirms that most of the time is spent allocating thing. I was wondering what would the standard way of using ndarray efficiently here.

**Comment by Jvanrhijn** [comment]
Still not as fast as the commented-out code, but I can cut the run time in more than half compared to the array operations by using `Zip`:

~~~rust
let mut x = Array1::<f32>::zeros(2);
let now = Instant::now();
for j in 1..512 {
  for i in 1..512 {
    azip!(mut x, a, u, v 
          in { *x = a + u * (step_x * i as f32) + v * (step_y * j as f32) });
    sum += buffer[(x[1].floor() * 3.0f32 + x[0].floor()) as usize];
  }
}
~~~

This cuts down on allocating `x` as well as the temporaries on each loop. The flamegraphs aren't very readable I'm afraid:

* Zip version:

![image](https://user-images.githubusercontent.com/13031225/62317551-3a71a380-b49a-11e9-9192-914137d49a02.png)

* Array operations version:
 
![image](https://user-images.githubusercontent.com/13031225/62317571-42c9de80-b49a-11e9-8486-dc3340f6d8b5.png)

* Bare bones version:

![image](https://user-images.githubusercontent.com/13031225/62317705-81f82f80-b49a-11e9-9bef-9e0950b3c789.png)

**Comment by jturner314** [comment]
Using `ndarray`, I'd suggest @Jvanrhijn's version. It's readable and eliminates all of the heap allocations in the loop.

However, if your problem consists only of vectors and matrices (especially small, constant-size vectors and matrices), you may consider the `nalgebra` crate instead of `ndarray`. The current implementations of these crates target different use-cases:

* `ndarray` provides n-dimensional arrays, and the length of each axis is dynamic (unknown at compile time). It's designed to have good performance when handling medium to large arrays, but since the axis lengths are dynamic and the contents of owned arrays are always heap-allocated, its performance won't be as good as `nalgebra` when dealing with small, constant-size (i.e. size known at compile time) vectors and matrices.

* `nalgebra` provides vectors (1-D) and matrices (2-D), and the length of each axis may be constant (known at compile time). It should have good performance in general, and should have better performance than `ndarray` when dealing with small vectors and matrices when the sizes are constant (known at compile time) because in this case (1) the compiler knows the sizes so it can perform more aggressive optimization and (2) the contents of the constant-size vectors/matrices are stack-allocated.

Basically, if you're dealing with small, constant-size vectors and matrices, `nalgebra` will probably provide better performance than `ndarray`. This is true even if you can eliminate `ndarray`'s heap allocations in hot spots (as in @Jvanrhijn's example using `Zip`). `ndarray` really targets use cases where you need medium to large, potentially higher-dimensional arrays.

If you need `ndarray`'s functionality in other parts of your code, you could use `nalgebra` optimize hot spots dealing with small, constant-size vectors/matrices.

Here's the `nalgebra` version of your example:

```rust
use nalgebra::Vector2;

fn main() {
    let buffer = vec![0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0];
    let a = Vector2::new(0.0, 0.0);
    let u = Vector2::new(1.0, 0.0);
    let v = Vector2::new(0.0, 1.0);
    let step_x = 3.0 / 512.0;
    let step_y = 3.0 / 512.0;
    let mut sum = 0f32;

    let now = Instant::now();
    for j in 1..512 {
        for i in 1..512 {
            let x = a + u * (step_x * i as f32) + v * (step_y * j as f32);
            sum += buffer[(x[1].floor() * 3.0f32 + x[0].floor()) as usize];
        }
    }
    println!("sum {:?}", sum);
    println!("{:?} ms", now.elapsed().as_nanos() as f64 / 1_000_000f64);
}
```

These are the results on my computer:

```
original
sum 1044484.0
34.079313 ms

using_zip
sum 1044484.0
16.900053 ms

nalgebra
sum 1044484.0
2.04463 ms
```
