### ISSUE TITLE
Adding Norms

### ISSUE THREAD

**Issue by JP-Ellis** [rust-ndarray/ndarray#694]
Would it be worth adding various `norm` functions?  In particular, I think the following might be useful:

- [L1-Norm (a.k.a. Manhattan Distance)](https://en.wikipedia.org/w/index.php?title=Manhattan_distanc): The sum of the absolute values
- [L2-Norm (a.k.a. Euclidean Norm)](https://en.wikipedia.org/wiki/Euclidean_norm): The square root of the sum of the squares
- [Lp-Norm](https://en.wikipedia.org/wiki/Lp_space#The_p-norm_in_finite_dimensions): The p-th root of the sum of the pth powers
- [L∞-Norm (a.k.a. Maximum Norm](https://en.wikipedia.org/wiki/Chebyshev_distance): The maximum of the absolute values

I'd be happy to work on a pull request to add these in.

These would all work on a single axis at a time, as the order in which you reduce the array matters.  The only exception to this is the L2-norm (where the taking the L2-norm of each row and then column, or each column and then row, or of the flattened array is the same)

**Comment by LukeMathWalker** [comment]
If I am not mistaken, most of these norms are available in the `deviation` module of `ndarray-stats`, currently on the master branch but not yet released. Could you check if they cover all the usecases you were thinking about?

**Comment by JP-Ellis** [comment]
Indeed they are!  With the exception of the Lp-norm, though admittedly that one is the rarest of the cases above as p is rarely anything else than 1, 2 and infinity.

**Comment by LukeMathWalker** [comment]
Do you think moving them into `ndarray` could make them easier to find? Or should we just add a pointer in `ndarray` docs (once they are released)? @JP-Ellis

**Comment by JP-Ellis** [comment]
I think it is nice separating them out into another array.  The documentation for `ndarray` is already a little overwhelming!

To avoid confusion, it would also be good if the functions that calculate the mean, standard deviation and variance were also move to `ndarray-stats`.

**Comment by rasa200** [comment]
Hi there, thank you for all the work!! 

I just wanted to add that I had a bit of travel finding the function. I was looking for the l_2 norm. This is was my sequence of thoughts:

1. Searched for `norm` in ndarray. 
Not found, so ovbiosly I looked for `dot`.

2. Since the `Dot` trait is part of the `linalg` module, I thought it could be in `ndarray_linalg` crate.
But `norm` is not there.

3. I came here to this post, but the reference for the [DeviationExt](https://docs.rs/ndarray-stats/0.3.0/ndarray_stats/trait.DeviationExt.html#tymethod.l2_dist) trait does not implement norms of vectors, but distances.
Of course, the norm is simply the distance to zero, but again, this is just as good workaround as using `dot` and `sqrt`. 

4. Conclusion: I will just use `dot` and `sqrt` for my use case: it does not add more dependencies and should be the default implementation(?)

I agree that the documentation for `ndarray` is already quite full, so I don't have a strong suggestion. Just wanted to let you know.

Cheers!

**Comment by black-puppydog** [comment]
I just want to echo @saona-raimundo's reply; I came here with the exact same questions and take-aways. (except that I was actually *also* searching for distance functions, so that's fortunate 🙂)

The workaround of `dot` and `sqrt` feels clunky. This is something I'd expect an ndarray implementation (or ecosystem) to include.
