### ISSUE TITLE
 Reflect removal of from_iter in #648 in documentation for 0.13.0

### ISSUE THREAD

**Issue by buchbend** [rust-ndarray/ndarray#779]
I am new to Rust and ndarray. Trying to learn how to work with both I still found references in the current documentation to 'from_iter'  which was removed in #648. For example here:
 
https://docs.rs/ndarray/0.13.0/ndarray/struct.ArrayBase.html#method.axis_chunks_iter

and in the 'ndarray_for_numpy_users' document. This got me stuck for a while until searching through the issues.

**Comment by jturner314** [comment]
Good catch on the `ndarray_for_numpy_users` document. I've created #780 to fix it. In the [`axis_chunks_iter`](https://docs.rs/ndarray/0.13.0/ndarray/struct.ArrayBase.html#method.axis_chunks_iter) example, note the

```rust
use std::iter::FromIterator;
```

(line 3); this is necessary to be able to call `Array::from_iter`. (`from_iter` is now provided only by the `FromIterator` trait. In previous versions of `ndarray`, there was an additional method directly on `ArrayBase`, but as you observed, PR #648 removed it. That's why you now need to `use std::iter::FromIterator` to be able to use `from_iter`.)

**Comment by buchbend** [comment]
Thanks a lot for the  fix and the explanation regarding `axis_chunks_iter` I understand much better now how to use it. Many thanks also for the great work on the ndarray implementation.
