### ISSUE TITLE
impl `Borrow<&ArrayBase<ViewRepr<&T>, _>>` for `ArrayBase<OwnedRepr<T>, _>`

### ISSUE THREAD

**Issue by garro95** [rust-ndarray/ndarray#878]
If possible, the trait specified in the title would make it easier to store owned arrays in a (Hash)Map and retrieve them without the need to build a new owned array (performing allocations).

**Comment by garro95** [comment]
Probably the implementation of `borrow` would be a simple `self.slice(s![..])` with `..` repeated for every axes

**Comment by jturner314** [comment]
Unfortunately, this is not possible in current Rust. (Who would own the `ArrayView` that `borrow` would return a reference to?) For the same reason, we can't return an `&ArrayView` from our [implementation of `Index`](https://docs.rs/ndarray/0.14.0/ndarray/struct.ArrayBase.html#impl-Index%3CI%3E).

To do something like this, we need the language to support custom dynamically-sized types, i.e. custom "fat pointers." (The shape/strides/etc. would be stored in the fat pointer itself.) It's worth noting that current proposals, e.g. rust-lang/rfcs#2594, would make it possible to return `&ArrayView` for constant-ndim cases (e.g. `Ix1`, `Ix2`, etc.), but they still wouldn't allow returning an `&ArrayView` for the `IxDyn` case.

**Comment by bluss** [comment]
The crate indexmap implements a more mechanism for this (instead of Borrow) - it's Equivalence trait should make it possible to implement this.

**Comment by jturner314** [comment]
I realized that my initial response was misleading. It's not possible to implement `Borrow<ArrayView<'a, A, D>> for ArrayBase<S, D> where S: Data` since it's not possible to correctly express the lifetime `'a`. However, it is possible for us to introduce a new data type `RefRepr` such that `&'a ArrayBase<RefRepr<A>, D>` is analogous to `ArrayView<'a, A, D>`, and we can implement `Borrow<ArrayBase<RefRepr<A>, D>>` and `Deref<Target = ArrayBase<RefRepr<A>, D>>` for `ArrayBase<S, D> where S: Data`. I'll write up my thoughts in a separate issue.
