### ISSUE TITLE
MulAssign operation is not being vectorized

### ISSUE THREAD

**Issue by TheButlah** [rust-ndarray/ndarray#882]
Hi, I'm using `ndarray` with the intent of leveraging it as easy vectorized tensor arithmetic. I did `*=` operation on a tensor against a lower dimensional tensor. My expectation is that this lower dimensional tensor would broadcast and then perform vectorized multiplication and assignment.

However, looking at the code path in the debugger, it looks like its hitting the `zip_mut_with` and `zip_mut_with_same_shape` functions, and it seems as though its not being done using SIMD vectorized instructions. Can you shed some light on whether this is vectorized or not, and how to tell?

Here's a fully reproducible piece of code that provides the full working example. The part I'm interested in is the `flush_and_skip` function, specificially the broadcasted multiplication on line 260 in `lib.rs`
[filter.zip](https://github.com/rust-ndarray/ndarray/files/5766121/filter.zip)

**Comment by bluss** [comment]
This operation can be autovectorized if the arrays are contiguous, there's nothing else that I know of - and ndarray does not contain any explicit vectorization at the moment - more than the matrix multiplication kernels from matrixmultiply.

**Comment by TheButlah** [comment]
How would I know if the operation is autovectorized?

**Comment by bluss** [comment]
I would normally use `perf` to record and investigate the hot code, from where you can tell (with some experience) if it's using simd instructions. I don't have any other way. Start with the assumption of - if ndarray can see it's a contiguous stretch of memory for the innermost dimension, on both sides of the operation, that part will probably be vectorized otherwise not.
