### ISSUE TITLE
trait MultiSlice is undocumented

### ISSUE THREAD

**Issue by dovahcrow** [rust-ndarray/ndarray#895]
It seems like we forget to pub use the MultiSlice?

See: https://docs.rs/ndarray/0.14.0/ndarray/index.html?search=multislice

**Comment by jturner314** [comment]
I did this intentionally while implementing #717 because I didn't really want to expose the `MultiSlice` trait itself as part of the public API. Part of the reason I'm hesitant to expose it right now is that the trait should be improved once Rust has generic associated types. (The `'a` and `A` should be moved to the `Output` associated type.)

Is there a particular reason to expose it other than for documentation purposes? If not, could we improve the documentation in other ways?

**Comment by dovahcrow** [comment]
@jturner314 Thanks for the reply! Yes, I agree that we can expose this trait once we have the GAT. 

Basically, I was trying to get a bunch of mutually disjointed mutable array views using `multi_slice_mut`. The problem I met was that what I got is a vector of ranges however the example in the documentation takes a tuple. I was trying to figure out what other types also implemented MultiSlice. However, the trait MultiSlice is unclickable due to being undocumented. 

I'm totally fine with hiding MultiSlice until GAT landed since I can also read the source code.
