### ISSUE TITLE
I'd like to contribute

### ISSUE THREAD

**Issue by stokhos** [rust-ndarray/ndarray#966]
Hi guys, 
I'd like to contribute to ndarray, is there any issues that I can work on to help me get familiar with the internal codes?

best

**Comment by jturner314** [comment]
There are a few issues tagged with [good first issue](https://github.com/rust-ndarray/ndarray/labels/good%20first%20issue) or [help wanted](https://github.com/rust-ndarray/ndarray/labels/help%20wanted). I'd recommend asking before starting work on one, though, in case the issue is out-of-date, and to discuss how to approach the implementation.

**Comment by bluss** [comment]
I can explain that the `src/impl_*` convention is for all files that are part of `impl ArrayBase`. The many inherent methods of that type and its aliases are quite spread out, naturally.

**Comment by stokhos** [comment]
Got it. Big thanks guys! @bluss @jturner314
