### ISSUE TITLE
An alternative way to represent dimensions before `const_generics` being stable

### ISSUE THREAD

**Issue by QuarticCat** [rust-ndarray/ndarray#984]
Demo:

```rust
struct Z;
struct S<N>(N);

struct Helper;

trait Min<N1, N2> {
    type Val;
}

impl<N1> Min<N1, Z> for Helper {
    type Val = Z;
}

impl<N2> Min<Z, S<N2>> for Helper {
    type Val = Z;
}

impl<N1, N2> Min<S<N1>, S<N2>> for Helper
where
    Helper: Min<N1, N2>,
{
    type Val = S<<Helper as Min<N1, N2>>::Val>;
}

fn min<N1, N2>(_a: N1, _b: N2) -> <Helper as Min<N1, N2>>::Val
where
    Helper: Min<N1, N2>,
{
    unimplemented!()
}

fn main() {
    min(S(Z), S(S(Z)));
}
```

[Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3228632c79b1c6bd1db0432b7b667957)

where `Ix0` is `Z`, `Ix1` is `S<Z>`, `Ix2` is `S<S<Z>>`, etc.

This makes it easy to extend dimensions.

You can also implement the trait like `DimMax`, i.e. `impl TypeFunction<RHS> for LHS` .

**Comment by jturner314** [comment]
Thanks for the suggestion. The [`typenum` crate](https://docs.rs/typenum/1.13.0/typenum/index.html) is implemented somewhat similarly. The problem with this type of thing is that it makes the code more difficult to work with, and I don't see much benefit to doing this for `ndarray`'s dimension types. In practice, arrays with more than six dimensions are very rare, so there isn't a strong motivation for const-ndim arrays above `Ix6` anyway. I'd prefer to do what we can with min const generics with const-ndim types up to `Ix6`, and only generalize to arbitrary-const-ndim arrays once Rust has full const generics.

**Comment by burrbull** [comment]
Not sure this is related the topic. Author of `nalgebra` use `Const` wrapper around const: https://github.com/dimforge/nalgebra/blob/dev/CHANGELOG.md#modified

**Comment by jturner314** [comment]
Thanks for the link. They also wrote a nice [blog post about integrating const generics into `nalgebra`](https://dimforge.com/blog/2021/04/12/integrating-const-generics-to-nalgebra/). Their approach is to use const generics where possible, and they convert to and from `typenum` types to perform computations on const generics. This makes sense for `nalgebra`, which allows specifying the shape with const generics, so it's imporant to support arbitrary const axis lengths. With `ndarray`, the shape is always dynamic; only the number of axes may be const. It's not very important to support arbitrary const ndim above a small threshold (currently 6 axes), so IMO the additional complexity outweighs the benefits of a `typenum`-style approach for computations on const ndims.

Fwiw, I do think that there are areas where `ndarray`'s dimension-related types can be improved (e.g. making the arrays generic over a type representing the number of dimensions, rather than a type representing the shape), but I don't think that a `typenum`-style approach would be beneficial for `ndarray`.

**Comment by bluss** [comment]
There is more that needs to be demo'd to show that it's viable since this is only the type system part. To replace the current dimension-to-slice code, at least an iterator of `usize` elements in the dimension would be needed and also `Index/Mut` impls. With that said, it probably doesn't matter right now. We haven't even explored `min_const_generics` yet. For all we know, that already does most of what we need.
