### ISSUE TITLE
Slicing an ArrayView restricts lifetime

### ISSUE THREAD

**Issue by cassiersg** [rust-ndarray/ndarray#988]
The following doesn't work, due to the signature of ArrayBase::slice.
```
fn foo<'a>(x: ArrayView1<'a, i32>) -> ArrayView<'a, i32> {
    x.slice(s![1..])
}
```
It would be nice to have a method dedicated to this on ArrayView, similarly to `ArrayView::to_slice`, (which is a taylor-adapted version of `ArrayBase::as_slice`).

**Comment by jturner314** [comment]
The [`slice_move`](https://docs.rs/ndarray/0.15.1/ndarray/struct.ArrayBase.html#method.slice_move) method on `ArrayBase` can be used for this purpose. If you don't want to lose access to the original view, note that const-ndim `ArrayView`s implement `Copy` and `Clone`, and dynamic-ndim `ArrayView`s implement `Clone`. However, I'm not opposed to adding a special method to `ArrayView` if we can come up with a good name for it, since there is a potential efficiency gain from a specialized implementation instead of `.clone().slice_move()`.

**Comment by cassiersg** [comment]
Thank you, I missed `slice_move`. I'll go with that. I guess overhead of `.clone().slice_move()` will be negligible except in rather rare situations.

**Comment by jturner314** [comment]
Yeah, for `ArrayView1` especially, you don't even need the `.clone()` since it implements `Copy`, and the overhead should be zero or negligible.

**Comment by cassiersg** [comment]
I opened #989 which would have helped me not miss the `.clone().slice_move()` solution. Re-perf: indeed, and also for any dimensionality as long as you deal with large matrices (and actually do something with them).

Leaving up to you to close this or not.

**Comment by jturner314** [comment]
Okay, I'll go ahead and close this.

To anyone coming across this issue: If `.clone().slice_move()` isn't good enough, and you need a method

```rust
impl<'a, A, D> ArrayView<'a, A, D> {
    fn foo<I>(&self, info: I) -> ArrayView<'a, A, I::OutDim> 
    where
        I: SliceArg<D>,
    { ... }
}
```

and have a good name for it, please feel free to reopen this issue or create a new one referencing it.
